[placeholders]
rust_toolchain_channel = { prompt = "Enter your rust toolchain channel", choices = ["nightly", "beta", "stable"], default = "nightly", type = "string" }

[template]
ignore = [ 
  ".idea",
]

[conditional.'crate_type == "lib"']
ignore = [ "src/main.rs" ]

[conditional.'crate_type == "bin"']
ignore = [ "src/lib.rs" ]